openapi: 3.0.0
info:
  title: Demo RDAP API
  version: 1.0.0
  description: Minimal endpoints for Security Copilot demos.
servers:
  - url: https://YOUR-FQDN
paths:
  /healthz:
    get:
      operationId: health
      responses:
        '200': { description: OK }
  /echo:
    get:
      operationId: echo
      parameters:
        - in: query
          name: text
          schema: { type: string }
          required: true
      responses:
        '200': { description: OK }
  /rdap/domain/{name}:
    get:
      operationId: rdapDomain
      parameters:
        - in: path
          name: name
          schema: { type: string }
          required: true
          description: Domain name (example.com)
        - in: query
          name: server
          schema: { type: string }
          required: false
          description: Optional RDAP base URL override
      responses:
        '200':
          description: RDAP JSON
          content:
            application/rdap+json:
              schema: { type: object, additionalProperties: true }
        '404': { description: Not found }
        '502': { description: Upstream error }
components: {}
